### ISSUE TITLE
I have a question about fixRPX

### ISSUE THREAD

**Issue by Joonie86** [wmltogether/BlackWaterUnpacker#1]
Hi there, I successfully compiled your Blackwaterpatcher.exe after installing ironpython 2.7.5
However, its unpacker and fixRPX don't seem working properly.
I was able to unpack the resource and fixed the main.elf by using blackwatertool.py
but unfortunately that blackwaterpacher keeps generating the same RPX file although it seems to repack archive00.lnk just fine.

I'm wondering if you could release or share your compiled working binary instead.

Thanks in advance.!

**Comment by wmltogether** [comment]
Currently my scripts only support the Japanese version Maiden of BlackWater. 
Since util.py is not an automatic tool for all RPXs, Other versions may have different zlib blocks in different offsets.
But you can search "789C" from the RPX file and change the zlib offset in BlackWaterPatcher/util.py, then find the filesize table from the block which you decompressed.

**Comment by Joonie86** [comment]
From my understanding, mainform.py also needs ported for US version..
I think I almost got it, but still couldn't figure this out 100% yet..

Could you take a look at my modified source with RPX/ELF?
http://www.mediafire.com/file/mt2wt2ns528a92u/BlackWaterPatcher_US.rar

**Comment by wmltogether** [comment]
I didn't check the "lfm_order.bin" from US version . But The US and the JAP version may have different file order.（you could download the JAP version and check the lfm_order.bin）. So ,you can't use `if 0 <= file_id <= 1409 ,1410 <= file_id <= 2526 ,2527 <= file_id <= 2643 ` directly.These ids are all JAP's file order.  It may cause black screen issue during game loading. 

Sorry for my poor English. : XD

**Comment by Joonie86** [comment]
Your English is perfect :)
By the way I'm still lost..
http://www.mediafire.com/file/54z2w5ltv6cok9m/BW.rar 
here are dpfilelists and lfm_order files , could you please take a look when you get a chance? thanks in advance!
