### ISSUE TITLE
How to use the tool?

### ISSUE THREAD

**Issue by Nekukun97** [wmltogether/BlackWaterUnpacker#2]
Sorry for the inconvenience, but could you explain how the tool is used? I've been investigating, but I can not figure out how to use it.

If you could do a minitutorial or put the instructions, I would greatly appreciate it.

Sorry for my bad english

**Comment by wmltogether** [comment]
You could follow these steps and have a try.
1. download a JAP version "零 ～濡鴉ノ巫女～", (US/EU versions have different file offsets, currently not supported )
2. you can Unpack the archive00.lnk pack  with PAK.unpack() method, and repack them with PAK.inject() method (see BlackWaterTool.py), unpack the pack and you will find *.msbt(text file) and *.bffnt(font)
BlackWaterPatcher is a Winform GUI patch tool written in IronPython. You can compile it with ipy `ipy pyc.py /standalone /main:Program.py MainForm.py util.py /embed /target:winexe /out:BlackWaterPatcher.exe`
4. translate *.msbt files , build a new font with FontConverter from WiiU SDK(or my font_tool ) and reinject with BlackWaterPatcher.

**Comment by Nekukun97** [comment]
Thank you very much, I have already been able to extract the file "archive00.lnk". Now I'm researching the Fonts, I do not  understand it yet.

**Comment by wmltogether** [comment]
Try this tool [FontConverter](https://drive.google.com/open?id=0B8aGRgqUf1t4V2NEQ1JOMEZUTXM)

**Comment by Nekukun97** [comment]
Sorry for the inconvenience, how do I get the file "main.elf"? The program tells me that it is used to patch the .rpx, but I can not find it.

**Comment by wmltogether** [comment]
Do you convert the rpx with rpl2elf?

**Comment by wmltogether** [comment]
these are all my project files. It contains all files lost in github repository.
https://drive.google.com/file/d/0B8aGRgqUf1t4dHFiN2JGXzREUUE/view?usp=sharing

**Comment by Nekukun97** [comment]
![img_20170406_213212283](https://cloud.githubusercontent.com/assets/26884214/24786103/b3d0ab9a-1b13-11e7-98f7-bdaf0d8244cb.jpg)

It works, Thank you so much for everything.
