### ISSUE TITLE
How to increase the amount of characters in cutscenes?

### ISSUE THREAD

**Issue by ghost** [wmltogether/BlackWaterUnpacker#4]
First of all, thanks for sharing the tool for translating Fatal Frame to other languages, I'm doing some tests, and I realized that during the cutscenes, the game has a character limit already stipulated, I would like some help to solve this problem.

An example:
At the end of the prologue, there is a scene after Miu gets stuck, in the cutscene I would like to put this text in English.

<a href="https://imgur.com/0swEnN9"><img src="https://i.imgur.com/0swEnN9.png" title="source: imgur.com" /></a>

But when I tested it, it was just this incomplete text.

<a href="https://imgur.com/hEifpgr"><img src="https://i.imgur.com/hEifpgr.png" title="source: imgur.com" /></a>

You know how to solve it, could you help me explaining how?
Thank you for the patience.

**Comment by wmltogether** [comment]
Well , I wrote some python sample scripts for msbt text parsing , have a look at  ‘text-tool’ folder , you will find these scripts

**Comment by ghost** [comment]
I don't have programming language knowledge, sorry.
For example, if I translate a file that is TEXT_TOOL\JPJA\jptext, then use repack_text.py and insert using BlackWaterPatcher.exe, shouldn't all characters appear in the cutscene?

**Comment by wmltogether** [comment]
copy `jptext` folder to a new folder renamed with your locale (like `frtext`), open `repack_text.py` using vscode,  find `line 136`, `cnlines = codecs.open("jpTEXT//%s.txt"%fn , "rb" , "utf-16").readlines()`, change `jpTEXT` to your new foloer (like `frtext`), translate these new files, then use `repack_text.py` to repack translations,  insert  the new translated msbt files in `import` folder with BlackWaterPatcher

**Comment by ghost** [comment]
Thanks for your help and for your patience.
I did all this procedure, but the same problem happens. the phrase keeps appearing only until the "sealed into a" and the rest doesn't appear in the cutscene. 
Here the text translated with Notepad++.
<a href="https://imgur.com/8w3yYbK"><img src="https://i.imgur.com/8w3yYbK.png" title="source: imgur.com" /></a>
I think there is some place where I can increase the number of characters used in this sentence so that it appears in the cutscene. Could it be in the .rpx file, or one of those files in the RTM folder
<a href="https://imgur.com/9pVzLh7"><img src="https://i.imgur.com/9pVzLh7.png" title="source: imgur.com" /></a>
or in the TRP_MOV_CMN.MSBT file itself?
TKS!

**Comment by wmltogether** [comment]
Sound like a hard-coded sentence length limitation in JPN version. The sentence Length in East-Asian languages always short than English, I didn't realize that problem. Ok, I will check the differences between JPN & US/EU versions

**Comment by ghost** [comment]
Nice, TKS!

**Comment by horxd33** [comment]
Some data
https://mega.nz/folder/B2RiBB4J#_ptBdBCRhfMIVfJDbkTjSw

**Comment by wmltogether** [comment]
Hmm, Could you replcae the main game font with eu version and tell me the result ?

**Comment by ghost** [comment]
If I rename [EU] Font VIVIENE.BFFNT to LENS5_SYSTEM_FONT.BFFNT and insert using BlackWaterPatcher.exe, it works normally, but Japanese characters no longer appear.

**Comment by wmltogether** [comment]
hmmm，
It seems that The ascii character width in JPN version are too large caused Game-UI text label truncated.
Try using Font Converter (from Wiiu sdk)  create a new font instead.

**Comment by wmltogether** [comment]
see 
 https://github.com/wmltogether/BlackWaterUnpacker/issues/2#issuecomment-291750965

**Comment by ghost** [comment]
Same problem.

<a href="https://imgur.com/liuwtxe"><img src="https://i.imgur.com/liuwtxe.png" title="source: imgur.com" /></a>

This problem occurs throughout the game, but you can insert new lines in other parts, only in cutscenes it is not possible to do this.

**Comment by wmltogether** [comment]
So ，It means the LENS5_SYSTEMFONT font file cause the truncated. but the VIVIENE font ok?
emmmmm… so strange..

**Comment by ghost** [comment]
VIVIENE works fine, I think the font is not the problem.
I believe the character limiter is some pointer in some file that uses some sync with the cutscenes.

**Comment by wmltogether** [comment]
but the VIVIENE works means the gui programs can  fit the text label correctly when using a suitable font config. emmmm

**Comment by ghost** [comment]
It should work, but for some reason in the cutscenes, it has a character limit. 
I have no idea what it might be.
It is very difficult to reprogram the tool to work in the EU or USA version, it would help a lot in the translation to other languages.
I don't know anything about programming, not even the basics.

**Comment by wmltogether** [comment]
I have no idea too.
Waiting for PC version

**Comment by ghost** [comment]
Yes I will wait, it will be out soon. Thanks for your help and for your patience.
See ya
