### ISSUE TITLE
I got error when using the py to unpack and pack file

### ISSUE THREAD

**Issue by MRAllenlee1** [wmltogether/BlackWaterUnpacker#5]
Hello,bro.Sorry to disturb u here,but I really have problems when use BlackWaterTool.py to unpack archive00 in cmd here.It shows me IOError:[Errno 2]No such file or directory:'dpfilelist.txt",the .py file can`t work normally,so I can`t use the function of unpacking and repack.Do you know how to solve it?or it`s because I use the wrong method to cause this?

**Comment by wmltogether** [comment]
Your python version ?
Put the script with game files together, run with python 2.7

**Comment by MRAllenlee1** [comment]
Thx for your reply,bro.
So I should download python 2.7 version,and then in the game path use cmd 
python BlackWaterTool.py D:\TEST\black\BlackWaterUnpacker-cafe\BlackWaterUnpacker\archive00
Is that correct?Sorry,bro,because this is my first time to use python,but I really love the game, so I`m finding the way to unpack it to mod the character mod,but I really go in mess with unpack and repack method hereXD.I saw your profile,are u a chinese?if you don`t mind it,could u add my QQ:454376514,I show you the error in py? I`ll really appreciate it~~

**Comment by wmltogether** [comment]
Learn python tutorials, open text editor and change the script to unpack mode instead of inject mode.

**Comment by wmltogether** [comment]
Python basics , issue closed

**Comment by wmltogether** [comment]
既然都发QQ了那肯定是国内老哥
打开脚本倒数第二行，inject改写unpack，用python 2.7跑 别用python3，记得和游戏文件都放在一起 lnk和lfm_order都要放

**Comment by MRAllenlee1** [comment]
好的，谢谢大佬，现在在开始运作解包了，谢谢啊，你解决了我一直的困惑，解压完我就准备研究下里面的文件了，上面的是我的Q，老哥不嫌弃的话可以加一下么，我不会一直问问题的，就怕遇到瓶颈情况，想说可以咨询一下

**Comment by MRAllenlee1** [comment]
老哥，我想咨询下，您做出来的这个UNPACKER包，解压出来的里面 GMPK, GAPK这些文件可以用里面的py解压么

**Comment by wmltogether** [comment]
都是光荣无双引擎的一些数据格式
用别的工具再解吧
https://forum.xentax.com/viewtopic.php?t=21679

**Comment by MRAllenlee1** [comment]
谢谢大佬，如果想重新打包回去，把UNPACK改回inject，CMD运行就可以了哇？ 我这边刚刚尝试了下 REPACK的时候显示的是IOError: [Errno 2] No such file or directory: 'import\\archive00.lnk'

**Comment by MRAllenlee1** [comment]
大佬，救救我呀，重新封包打包回去 我把脚本里面改回inject后CMD运行PY显示IOError: [Errno 2] No such file or directory: 'import\archive00.lnk' 这个怎么解决呀~

**Comment by MRAllenlee1** [comment]
然后我尝试在路径下建了个import文件夹，把archive00丢进去了，运行PY CMD又提示IOError: [Errno 2] No such file or directory: 'import\\main.elf'  这个main.elf不知道在哪里找啦，大佬，我的封包步骤是不是不争取呀

**Comment by wmltogether** [comment]
main.elf是通过rpl2elf 把lens5_cafe.rpx转换成标准elf后的产物，脚本通过强制写入LBA到elf再压缩回rpx来达到修正压缩包文件偏移，rpl2elf这东西有五六年了，不知道外网有没有人存下来过

**Comment by MRAllenlee1** [comment]
好的，我找一下，然后把RPX转换成ELF，老哥，我那个操作是对的吧？如果要REPACK，在原路径下创建个IMPORT文件夹，然后文件夹里PY让我放三个东西 一个archive.lnk  一个elf 一个backup.rpx 我想问下，archive.lnk这个是放那个很大的原始文件么，然后backup.rpx去哪里找呀，把lens5_cafe.rpx重命名放进么。我现在对文件已经进行了修改，然后想重新打包成lnk，不知道怎么搞

**Comment by MRAllenlee1** [comment]
rpl2elf我找到已经转换出来啦，现在import文件夹里我放的有原始的archive.lnk 转换后的main.elf 以及改名后的backup.rpx  这三个文件操作是对的么，然后我要把自己修改的文件植入进去的话修改的文件应该怎么放呀，老哥

**Comment by MRAllenlee1** [comment]
大佬，我发现模型文件就是在.gmpk之中，上面给到这个链接解压不了濡鸦里的这个模型文件，因为是big endian的文件，那个网站说工具不支持big endian，老哥有办法可以弄一个.gmpk的 解包和打包工具么 卡在这里好几天啦，我去网上有没有搜到可以解包这的工具T.T

**Comment by wmltogether** [comment]
写工具也不是动动手指就解析的是不是，要不你请那位大佬改成支持be的😓

**Comment by MRAllenlee1** [comment]
这个大佬我联系过啦，说的是没有WIIU的游戏，改不了 T.T 其实我就是想简单实现模型之间的替换，比如把濡鸦里犀利替换成深红，但我发现直接替换gmpk的话游戏读取不了，然后我看网上有个大哥做了 BMS脚本可以从GMPK里把 G1M（模型） GIT（贴图）提取出来的，CODE如下：
GIM的
endian big
for i
findloc start string "G1M_0036"
goto start
print "%start%"
savepos offset
getdstring null 0x8
get size long
get NAME filename
string name + ".g1m"
log name offset size

next i

GIT的
endian big
for i
findloc start string "G1TG0060"
goto start
print "%start%"
savepos offset
getdstring null 0x8
get size long
get NAME filename
string name + ".g1t"
log name offset size

next i

我试了下可以提取出来成功，但是有个问题就是提取出来后我替换掉G1M和G1T quickmas提醒我要打包的文件比原文件大，所以没办法重新repack回去了，而且G1M会提取出5个重名的文件，后面重新打包的时候也无法识别怎么再打包回去，大佬可以帮帮忙么，目前理解的是 解包出来的G1M和G1T替换成原来的然后再封包成GMPK就可以了，目前就是卡死在了打包封包这一块无解了 T.T
