### ISSUE TITLE
repackage archive00

### ISSUE THREAD

**Issue by Narublack** [wmltogether/BlackWaterUnpacker#6]
Hello, I changed from BlackWaterTool.py the line 317 of pak.unpack that served me to extract the archive00.lnk to pak.inject.  having a folder called import with the files main.elf, backup.rpx and the original archive00.lnk creates me only lens5_cafe.rpx.  what kind of command do i need or why doesn't it pack archive00_lnk folder to archive00.lnk.  I couldn't create the executable file.  I don't understand ironpython program

**Comment by wmltogether** [comment]
Create a folder called "patch", put files you want to inject, then inject.
It would be append to the end of archive00.lnk and auto fix LBA
